### ISSUE TITLE
Migrate dependencies away from JCenter

### ISSUE THREAD

**Issue by oraNod** [bmuschko/asciidoctorj-tabbed-code-extension#5]
JCenter is going to be sunset according to this blog post: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I work as part of the Infinispan community project and we'd like to start using the tabbed code extension in our docs. There are some concerns around adding dependencies to artifacts that come from a repository that is going to disappear. Are there any plans to host the extension elsewhere? 

Thank you.

**Comment by bmuschko** [comment]
Great to hear. I am aware of the fact that JCenter will go away but didn't have the time to address it yet. I just synced the library from JCenter to Maven Central. The artifacts should become available within a day or so. Long term, I will want to change my publishing code to publish to Maven Central directly.

**Comment by oraNod** [comment]
That's great! Thanks so much, Benjamin. I'll confirm when the artifacts are on Maven Central and will close this issue.

**Comment by oraNod** [comment]
Thanks @bmuschko I see the library is on Maven Central now: https://search.maven.org/search?q=a:asciidoctorj-tabbed-code-extension
